
all:
	@g++ -oBurbuja.bin Burbuja.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo iterativo con ./Burbuja.bin salida_burbuja.txt 12345 1000 2000 3000
	@g++ -oMergeSort.bin mergesort.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./MergeSort.bin salida_mergesort.txt 12345 1000 2000 3000
	@g++ -oMaximoMinimoDyV.bin MaximoMinimoDyV.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./MaximoMinimoDyV.bin salida_maximominimo.txt 12345 1000 2000 3000
	@g++ -oheapsort.bin heapsort.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./heapsort.bin salida_heapsort.txt 12345 1000 2000 3000
